### ISSUE TITLE
firmware_titles.db updated up to 10.2.0

### ISSUE THREAD

**Issue by Buzbee** [shchmue/FVI#1]
Here is an updated firmware_titles.db that supports up to 10.2.0

[firmware_titles.zip](https://github.com/shchmue/FVI/files/5426646/firmware_titles.zip)

**Comment by shchmue** [comment]
looks like you added the firm a ncaids under 'svt'. those are supposed to be the ncaids for the system version title.
fixed in https://github.com/shchmue/FVI/commit/0df80ed7c83ea9a2a862c9f2cc04f8e3e8da3ca2

**Comment by Buzbee** [comment]
Not sure what you are saying.

I got it from

 https://github.com/eliboa/NxNandManager/blob/master/NxNandManager/NxStorage.cpp

All other versions match between your list and his. He also had two more:

{ "8.1.1", "e9bb0602e939270a9348bddd9b78827b.nca"}, /* 8.1.1-12  from chinese gamecard */
    { "8.1.1", "724d9b432929ea43e787ad81bf09ae65.nca"}, /* 8.1.1-100 from Lite */

Please verify wether you or I was right.

**Comment by shchmue** [comment]
i see what they did, they used the ncaid for the cmnt ncas for the system version title. i've been using the main ncaid. doesn't make a real difference.

**Comment by Buzbee** [comment]
Yes. I  have tested both your new db file and the one one I edited. I can confirm both ncas work on 10.2.0.
