### ISSUE TITLE
Most recent boot always 1980-01-01 00:00:00

### ISSUE THREAD

**Issue by rlaphoenix** [shchmue/FVI#12]
The specific system these dumps likely never connected to Nintendo but has connected to Wifi under 90DNS. I could be wrong, but its likely. This reason could be related, maybe I'm wrong but I thought I'd mention it anyway.

For reference I have 3x dumps from the same system. 1x dump from 2019 (unsure what was used), 2x dumps from today via Hekate of SysMMC (12.0.2) and EmuMMC (15.0.1).

All three dumps return `Most recent boot: 1980-01-01 00:00:00`, though technically the one from 2019 fails and does not get anything at all about the recent boot.

**Comment by shchmue** [comment]
Yeah, I used I think an imperfect method here. I am not interested in maintaining this project though, it was very janky. Try [NxNandManager](https://github.com/eliboa/NxNandManager)
