### ISSUE TITLE
eMMC (SysMMC) rawnand dump failing to find System Version Title

### ISSUE THREAD

**Issue by rlaphoenix** [shchmue/FVI#13]
I have 3x dumps from the same system. 1x dump from 2019 (unsure what was used), 2x dumps from today via Hekate of SysMMC (12.0.2) and EmuMMC (15.0.1).

I'm not currently considering this to be an issue with the firmware database simply because it should be around 12.0.2 or earlier, not later, even though up to 15.0.1 is supported.

The recent dumps via Hekate work, but the dump from 2019 does not.
If it's possible for me to safely send you a copy of the NAND (censored or not), let me know.

```
Firmware Version Inspector - by shchmue

Dump is full EMMC raw NAND.
Loaded BIS keys.

Found FAT boot sector!

Scanning root for /Contents/...
/Contents/ found at cluster 0x3 address 0x148000

Scanning root for /save/...
/save/ found at cluster 0x3c7c address 0xf32c000

Scanning /save/ for System Savegame 8000000000000060...
Success! Found /save/8000000000000060.

Scanning /Contents/ for /registered/...
/registered/ found at cluster 0x5 address 0x150000

Scanning FAT for fragmentation...
/registered/ clusters:  ['0x5', '0x2463', '0x14c75', '0x1909d']
Buffered 4 /registered/ clusters. Reading filenames...

Success! Found 186 NCA filenames.
System Version Title not found!
```

(the log data, offsets, bytes, clusters, e.t.c e.t.c, is pretty much an exact copy of the log for the recent SysMMC dump from Hekate, minus the error on the last line, I'm expecting 12.0.2)

**Comment by rlaphoenix** [comment]
Someone on nh discord got my Save Data 8000000000000120 file and thinks its v10.2.0, if that helps.

**Comment by shchmue** [comment]
See #12
