### ISSUE TITLE
Add firmwares upper than 12.1.0

### ISSUE THREAD

**Issue by shadow2560** [shchmue/FVI#3]
Hi,

I see there is no update since firmware 12.1.0, if you could add the new firmwares in the titles.db it could be usful for me to integrate this in NXNandManager. Or else if you can explain to me how to obtain by myself these informations I could do it and even propose a pull request.

Thanks for all.

**Comment by shchmue** [comment]
Here's how I do it: I go to https://yls8.mtheall.com/ninupdates/reports.php and open the page for the corresponding system version, then select the report under All. For 12.1.0, the page is https://yls8.mtheall.com/ninupdates/titlelist.php?date=2021-07-06_00-05-06&sys=hac . Then for the system version title I search the page for the 0100000000000809 entry that has `ncatype2`. The numbers after that identifier are the NCA id, `9d9d83d68d9517f245f3e8cd7f93c416` in this case. Then I look for 010000000000081B and find `ncatype2` has id `25bb90ed24664b791d0e2cc1b707ea30`. If you collect the updates on computer locally you can do similar with, for example, `hactoolnet -t switchfs [firmwarepath] --listncas | grep 0100000000000809`.
